version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: gustavofdeoliveira/m7-p2-backend
    restart: always
    ports:
      - "3001:3001"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # image: gustavofdeoliveira/m7-p2-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
